/*
 * This source file was generated by the Gradle 'init' task
 */
package lab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import lab.Lab;

class LabTest {
    @Test void appHasAGreeting() {
        Lab classUnderTest = new Lab();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
